### ISSUE TITLE
Broken invariant in chunkedTransferEncoding?

### ISSUE THREAD

**Issue by sjakobi** [lpsmith/blaze-builder#18]
When splitting the output of `chunkedTransferEncoding` into strict bytestrings, the result usually looks somewhat like this:

```
λ> import qualified Data.ByteString as S
λ> import qualified Data.ByteString.Lazy as L
λ> import qualified Data.ByteString.Builder as B
λ> import Blaze.ByteString.Builder.HTTP 
λ> f n = L.toChunks . B.toLazyByteString . chunkedTransferEncoding . B.byteString $ S.replicate n 95
λ> f 12
["00C\r\n____________\r\n"]
```

Each bytestring forms a complete chunk in the sense of [RFC 7230 Section 4.1](https://tools.ietf.org/html/rfc7230#section-4.1). From this observation I got the assumption that the 1-to-1 correspondence between bytestrings in the output and transfer chunks should be an invariant of `chunkedTransferEncoding`.

As I found out during some property testing that (supposed) invariant doesn't hold for certain larger inputs – the smallest "monolithic" input breaking it being a bytestring of length 8161:

```
λ> f 8161
["1FE1\r\n","___<snip>___","\r\n"]
```

In other tests I also found chunks like this:

```
...___", "\r\n2276\r\n___...
```

So my question is: Is this supposed to be an invariant of `chunkedTransferEncoding`?

(Ping @meiersi, who wrote `chunkedTransferEncoding`)

**Comment by afcowie** [comment]
ping @gregorycollins who has far more production experience with this than I do. He's the one that put me on to using the `chunkedTransferEncoding` funciton way back.

**Comment by meiersi** [comment]
Hi Simon, this is not and was not supposed to be an invariant. When
inserting a ByteString directly into the output stream using
Data.ByteString.Builder.Extra.byteStringInsert then there is no "free
space" for the termination token, which is why it will be output in the
next buffer. The function Data.ByteString.Builder.byteString inserts a
bytestring as-is if it is large enough. See
http://hackage.haskell.org/package/bytestring-0.10.8.2/docs/src/Data.ByteString.Builder.Internal.html#byteString


Andrew Cowie <notifications@github.com> schrieb am Mo., 19. März 2018 um
04:17 Uhr:

**Comment by sjakobi** [comment]
Thanks for clearing that up, @meiersi! :)
